import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chris Wolfe</title>
        <meta name="Portfolio Website for Christopher Wolfe" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
				<section className={styles.welcome}>
					<h4>Hello, I'm</h4>

					<h1 className={styles.title}>
						Christopher Wolfe;
					</h1>

					<p className={styles.description}>
						This is about You. But if you want to know, here is a bit <Link href='#about'><a className='about-me'>about me ⤵</a></Link>
					</p>

				</section>

				<section id='about' className={styles.about}>
					<h2>About me.</h2>
				</section>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
