import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Nav from "../components/Nav";
import Welcome from "../components/Welcome";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chris Wolfe</title>
        <meta
          name="Portfolio Website for Christopher Wolfe"
          content="Generated by create next app"
        />
      </Head>

      <main className={styles.main}>
        <Nav />

        <Welcome />

        <About />

        <Projects />

        <Contact />
      </main>
    </div>
  );
}
